### ISSUE TITLE
Training Resume Error

### ISSUE THREAD

**Issue by ashuezy** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#15]
```
21-09-13 21:50:38.132 - INFO: Loading pretrained model for G [experiments/sr_ffhq_210913_210552/checkpoint/I10000_E1] ...
Traceback (most recent call last):
  File "sr.py", line 51, in <module>
    diffusion = Model.create_model(opt)
  File "/opt/github/Image-Super-Resolution-via-Iterative-Refinement/model/__init__.py", line 7, in create_model
    m = M(opt)
  File "/opt/github/Image-Super-Resolution-via-Iterative-Refinement/model/model.py", line 23, in __init__
    self.load_network()
  File "/opt/github/Image-Super-Resolution-via-Iterative-Refinement/model/model.py", line 162, in load_network
    self.optG.load_state_dict(opt['optimizer'])
AttributeError: 'DDPM' object has no attribute 'optG'
```

**Comment by ErezYosef** [comment]
Hi,
I face it myself minutes ago.
Move the line :
https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/blob/ab8934b957663ce4b40d92450baa3ab287f6e0af/model/model.py#L23
to the end of __init__ function.

**Comment by Janspiry** [comment]
Yes，I am also found this error, and fix it now by moving `load_network() ` to define `self.optG`.
