### ISSUE TITLE
Error(s) in loading state_dict for GaussianDiffusion

### ISSUE THREAD

**Issue by Jotschi** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#32]
Seeing `Error(s) in loading state_dict for GaussianDiffusion` when trying to load the model `I1560000_E91`. 
I tried to use pytorch 1.7.1, python 3.7 to load the model. Was this also the version used to train it?

```
21-11-14 04:14:05.699 - INFO: Dataset [LRHRDataset - CelebaHQ] is created.
21-11-14 04:14:05.699 - INFO: Initial Dataset Finished
21-11-14 04:14:06.367 - INFO: Loading pretrained model for G [experiments/I1560000_E91] ...
Traceback (most recent call last):
  File "infer.py", line 46, in <module>
    diffusion = Model.create_model(opt)
  File "/home/jotschi/workspaces/ml/Image-Super-Resolution-via-Iterative-Refinement/model/__init__.py", line 7, in create_model
    m = M(opt)
  File "/home/jotschi/workspaces/ml/Image-Super-Resolution-via-Iterative-Refinement/model/model.py", line 42, in __init__
    self.load_network()
  File "/home/jotschi/workspaces/ml/Image-Super-Resolution-via-Iterative-Refinement/model/model.py", line 158, in load_network
    gen_path), strict=False)
  File "/home/jotschi/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GaussianDiffusion:
        size mismatch for denoise_fn.downs.0.weight: copying a param with shape torch.Size([64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 6, 3, 3]).
        size mismatch for denoise_fn.downs.5.res_block.noise_func.noise_func.0.weight: copying a param with shape torch.Size([128, 64]) from checkpoint, the shape in current model is torch.Size([256, 64]).
        size mismatch for denoise_fn.downs.5.res_block.noise_func.noise_func.0.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
```

**Comment by Janspiry** [comment]
Hi,` infer.py` is for super-resolution task. I think you should not use pre-trained model for generation task.

**Comment by Jotschi** [comment]
The same error also happens when running test/eval. I assume the pytorch versions don't match up. Which versions were used for the model?

**Comment by Janspiry** [comment]
![image](https://user-images.githubusercontent.com/32922494/141684417-a6c2573d-5f21-4a0e-bb2a-27c93a82f1df.png)
Maybe you should check the input size.
