### ISSUE TITLE
Infer.Py needs to be rewritten

### ISSUE THREAD

**Issue by YoussefSultan** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#35]
Traceback (most recent call last):
  File "infer.py", line 40, in <module>
    val_set = Data.create_dataset(dataset_opt, phase)
  File "/content/Image-Super-Resolution-via-Iterative-Refinement/data/__init__.py", line 34, in create_dataset
    need_LR=(mode == 'LRHR')
  File "/content/Image-Super-Resolution-via-Iterative-Refinement/data/LRHR_dataset.py", line 30, in __init__
    '{}/sr_{}_{}'.format(dataroot, l_resolution, r_resolution))
  File "/content/Image-Super-Resolution-via-Iterative-Refinement/data/util.py", line 16, in get_paths_from_images
    assert os.path.isdir(path), '{:s} is not a valid directory'.format(path)
AssertionError: dataset/celebahq_64_512/sr_64_512 is not a valid directory

**Comment by Janspiry** [comment]
I noticed it, thanks.
