### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'norm_groups'

### ISSUE THREAD

**Issue by a43501** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#9]
when running using following command:
python sr.py -p val -c config/sr_ddpm_16_128.json
I get following error:

```
(pytorch_env) admin@Admins-MacBook-Pro sr3 % python sr.py -p val -c config/sr_ddpm_16_128.json
export CUDA_VISIBLE_DEVICES=0
21-09-09 17:32:40.626 - INFO:   name: sr_ffhq
  phase: val
  gpu_ids: [0]
  path:[
    log: experiments/sr_ffhq_210909_173240/logs
    tb_logger: experiments/sr_ffhq_210909_173240/tb_logger
    results: experiments/sr_ffhq_210909_173240/results
    checkpoint: experiments/sr_ffhq_210909_173240/checkpoint
    resume_state: Users/admin/sr3/pretrained/I640000_E37
    experiments_root: experiments/sr_ffhq_210909_173240
  ]
  datasets:[
    train:[
      name: FFHQ
      mode: HR
      dataroot: dataset/ffhq_16_128
      datatype: img
      l_resolution: 16
      r_resolution: 128
      batch_size: 12
      num_workers: 8
      use_shuffle: True
      data_len: -1
    ]
    val:[
      name: CelebaHQ
      mode: LRHR
      dataroot: dataset/celebahq_16_128
      datatype: img
      l_resolution: 16
      r_resolution: 128
      data_len: 3
    ]
  ]
  model:[
    which_model_G: ddpm
    finetune_norm: False
    unet:[
      in_channel: 6
      out_channel: 3
      inner_channel: 64
      channel_multiplier: [1, 1, 2, 2, 4, 4]
      attn_res: [16]
      res_blocks: 2
      dropout: 0.2
    ]
    beta_schedule:[
      train:[
        schedule: linear
        n_timestep: 2000
        linear_start: 0.0001
        linear_end: 0.02
      ]
      val:[
        schedule: linear
        n_timestep: 100
        linear_start: 0.0001
        linear_end: 0.02
      ]
    ]
    diffusion:[
      image_size: 128
      channels: 3
      conditional: True
    ]
  ]
  train:[
    n_iter: 1000000
    val_freq: 10000.0
    save_checkpoint_freq: 10000.0
    print_freq: 200
    optimizer:[
      type: adam
      lr: 0.0001
    ]
    ema_scheduler:[
      step_start_ema: 5000
      update_ema_every: 1
      ema_decay: 0.9999
    ]
  ]
  distributed: False

21-09-09 17:32:40.643 - INFO: Dataset [LRHRDataset - CelebaHQ] is created.
21-09-09 17:32:40.644 - INFO: Initial Dataset Finished
Traceback (most recent call last):
  File "sr.py", line 51, in <module>
    diffusion = Model.create_model(opt)
  File "/Users/admin/sr3/model/__init__.py", line 7, in create_model
    m = M(opt)
  File "/Users/admin/sr3/model/model.py", line 16, in __init__
    self.netG = self.set_device(networks.define_G(opt))
  File "/Users/admin/sr3/model/networks.py", line 91, in define_G
    model = unet.UNet(
  File "/Users/admin/sr3/model/ddpm_modules/unet.py", line 218, in __init__
    self.final_conv = Block(pre_channel, default(out_channel, in_channel), norm_groups=norm_groups)
TypeError: __init__() got an unexpected keyword argument 'norm_groups'
```

**Comment by Janspiry** [comment]
I am so sorry for this error. 
You can change the `norm_groups=norm_groups` to `groups=norm_groups`, and I recommend you use the `sr3` module with pretrained model.

**Comment by a43501** [comment]
Hi, @Janspiry, thank you for your fast response!
